service: serverless-http-api
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs16.x

functions:
  hello:
    handler: handler.hello
    events:
      - httpApi:
          path: /
          method: get

plugins:
  - serverless-offline
  - serverless-sentry

custom:
  sentry:
    dsn: https://590d20d9dcf0460c9efc3b21fa5a241d@o219778.ingest.sentry.io/6694735
    organization: deepbaysz-bd
    project: new-lambda-sentry
    authToken: cb6a0f8f67674ca1a01bfdee4f4c35ce
    filterLocal: false